[package]
name = "devicemapper"
version = "0.4.1"
authors = ["Andy Grover <agrover@redhat.com>"]
description = "A library for using Linux device mapper"
documentation = "https://docs.rs/crate/devicemapper/"
# homepage = "..."
repository = "https://github.com/stratis-storage/devicemapper-rs"
readme = "README.md"
keywords = ["Linux", "device", "mapper", "libdm", "storage"]
license = "MPL-2.0"

[[bin]]
name = "dmtest"
path = "src/bin/dmtest.rs"

[dependencies]
libc = "0.2"
nix = "0.5"
bitflags = "0.4"
clippy = { version = "0", optional = true }
newtype_derive = "0.1"
custom_derive = "0.1"
serde = "0"
